# $schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: en-us
dictionaryDefinitions:
  - name: blog-words
    path: ./.cspell/blog-words.txt
  - name: fp
    path: ./.cspell/fp.txt
  - name: math
    path: ./.cspell/math.txt
  - name: tikz
    path: ./.cspell/tikz.txt
  - name: jsxgraph
    path: ./.cspell/jsxgraph.txt
  - name: tools
    path: ./.cspell/tools.txt
  - name: web
    path: ./.cspell/web.txt
  - name: hugo
    path: ./.cspell/hugo.txt
  - name:  scripts
    path: ./.cspell/scripts.txt
dictionaries:
  - blog-words
  - fp
  - math
  - tikz
  - jsxgraph
  - tools
  - web
  - hugo
  - scripts
useGitignore: true
ignorePaths:
  - themes
  - .cspell
  - .ltex
